development:
  adapter: postgresql
  encoding: utf8
  database: doners_api
  pool: 5
  username: postgres
  password: Sajith123

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: doners_api
  pool: 5
  username: postgres
  password: Sajith123

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username:
  password:
