# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f352586d76340842b6a98d0bcdbec868091f77194477310d596769db8500cde5121dd79ed4a6a7402dbce03953e6498168f95381e970875c8de22c43dfa4a23a

test:
  secret_key_base: e62bfa3ef31f53bc73ee12d10840de9c881ac19468134bafcbded920b489fae94bf19d49a4adea1f9ed4901d8bf5f56d9fdfee6e2927af486f2cb559032385f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
